### ISSUE TITLE
naver담당자님과 의논해야할 사항들

### ISSUE THREAD

**Issue by alphecca** [NaverSnu-MusicProject/work#8]
**0324.md 회의록을 참고하시면 됩니다.**

https://github.com/NaverSnu-MusicProject/meetings/blob/master/0324.md

회의하면서 궁금한 점들을 회의록에 기록해두었습니다만, 주된 궁금증은 다음과 같습니다.

- 저희가 이해한(의도하는) 바로는 다음과 같은 모식도를 그릴수 있을 거같은데, 담당자님이 생각하시는 구조도 바로 이와 같은지 궁금합니다.

![image](https://cloud.githubusercontent.com/assets/15091963/24303496/93066734-10f9-11e7-9527-6f828c5c74ac.png)

- 전에 네이버에서는 log형태로 정보를 준다고 하셨던 거같은데, '입력되는 정보를 로그로 남기는 시스템'이란 구체적으로 어떤 방식인가요?

- 평가표에 slack과 같은 협업 tool을 명시하셨는데, 반드시 slack을 이용해야 하나요?

**Comment by wlxyzlw** [comment]
+ 가장 중요한 것으로 저희 최종 목표가 웹 페이지 개발인가요? 아니면 API 제공인가요? 아님 둘다??

**Comment by alphecca** [comment]
3월 29일에 만나서 의논하였으므로 대강의 질문들이 해결된 것 같습니다.
@wlxyzlw 확인해보시고 닫아주세요.
